fragment PostParts on Post {
  __typename
  title
  description
  pubDate
  draft
  heroImage
  authorName
  authorAvatar
  body
  tags
}

fragment NewsletterParts on Newsletter {
  __typename
  title
  summary
  pubDate
  draft
  body
}

fragment SiteConfigParts on SiteConfig {
  __typename
  SiteName
  SiteDescription
  name
  jobTitle
  position
  picture
  avator
  socialLinks {
    __typename
    twitter
    linkedin
    github
    upwork
    youtube
    whatsNumber
  }
  about {
    __typename
    whoAmI
    lifeBeyondCode
    continuousLearning
  }
  techStack {
    __typename
    category
    tools
  }
  workExperience {
    __typename
    companyName
    position
    employmentTime
    roles
    toolsUsed
  }
}

fragment FeatureFlagsParts on FeatureFlags {
  __typename
  featureFlags {
    __typename
    showBlog
    showAbout
    showContact
    showProjects
    showIndex
    showTags
    showSearch
    showNewsletter
    showPrivacy
    showTermsOfService
    showSubNewsletter
    showTrendingPosts
    showTermsandConditions
    showPrivacyPolicy
    showIdeaPanel
  }
  FeatureFlagsApi {
    __typename
    enableauthorInfoAPI
  }
}

fragment PopularBlogsParts on PopularBlogs {
  __typename
  popularBlogs {
    __typename
    Page
    Visitors
    Total
  }
}
