fragment PostParts on Post {
  title
  description
  pubDate
  draft
  heroImage
  authorName
  authorAvatar
  body
}

fragment NewsletterParts on Newsletter {
  title
  summary
  pubDate
  draft
  body
}
