fragment PostParts on Post {
  title
  description
  pubDate
  draft
  heroImage
  authorName
  authorAvatar
  body
  tags
}

fragment NewsletterParts on Newsletter {
  title
  summary
  pubDate
  draft
  body
}

fragment ProjectsParts on Projects {
  Projecttitle
  ProjectDescription
  ProjectImage
  draft
  ProjectTech
  ProjectCategory
  body
}
