// src/data/popularBlogs.ts
export const popularBlogs = [
  { Page: "/", Visitors: 198, Total: 298 },
  { Page: "/blog/flutter_fork_flock", Visitors: 74, Total: 82 },
  { Page: "/blog/automate-life-in-linux", Visitors: 27, Total: 30 },
  { Page: "/blog", Visitors: 26, Total: 37 },
  { Page: "/blog/embrace_ai_tools", Visitors: 21, Total: 28 },
  { Page: "/blog/ai-coding-machine-learning", Visitors: 13, Total: 17 },
  { Page: "/about", Visitors: 8, Total: 8 },
  {
    Page: "/blog/make-money-from-open-source-software",
    Visitors: 8,
    Total: 11,
  },
  { Page: "/project", Visitors: 7, Total: 11 },
  { Page: "/tag", Visitors: 6, Total: 10 },
  { Page: "/blog/search-on-static-site", Visitors: 5, Total: 7 },
  { Page: "/contact-me", Visitors: 5, Total: 5 },
  { Page: "/newsletter-subscribe", Visitors: 3, Total: 3 },
  { Page: "/search", Visitors: 3, Total: 5 },
  { Page: "/api/notion", Visitors: 1, Total: 1 },
  { Page: "/blog-placeholder-1.jpg", Visitors: 1, Total: 1 },
  { Page: "/blog/deploy-your-application-the-journey", Visitors: 1, Total: 5 },
  { Page: "/blog/diy-ai-chatbot", Visitors: 1, Total: 1 },
  {
    Page: "/blog/exploring-react-a-full-stack-developers-perspective",
    Visitors: 1,
    Total: 1,
  },
  { Page: "/blog/mylovehaterelationshipwithcopilot", Visitors: 1, Total: 2 },
  { Page: "/blog/no-code-tools", Visitors: 1, Total: 1 },
  { Page: "/blog/text-search-application-python", Visitors: 1, Total: 1 },
  { Page: "/contact", Visitors: 1, Total: 1 },
  { Page: "/privacy-policy", Visitors: 1, Total: 1 },
  { Page: "/project/shafiqlawchamber", Visitors: 1, Total: 1 },
  { Page: "/tags", Visitors: 1, Total: 1 },
];
