export const containerStyles = {
	diagram:
		"relative bg-[#1a1b26] rounded-lg border border-[#565f89]/30 p-4 md:p-6 my-4 overflow-hidden",
	svgWrapper: "flex justify-center w-full overflow-x-auto",
} as const;

export const mermaidConfig = {
	theme: "base" as const,
	themeVariables: {
		primaryColor: "#7aa2f7",
		primaryTextColor: "#c0caf5",
		primaryBorderColor: "#7aa2f7",
		lineColor: "#7aa2f7",
		secondaryColor: "#bb9af7",
		tertiaryColor: "#565f89",
		background: "#1a1b26",
		mainBkg: "#24283b",
		secondaryBkg: "#414868",
		tertiaryBkg: "#565f89",
		secondaryTextColor: "#a9b1d6",
		tertiaryTextColor: "#9aa5ce",
		secondaryBorderColor: "#bb9af7",
		tertiaryBorderColor: "#565f89",
		noteBkgColor: "#24283b",
		noteTextColor: "#c0caf5",
		noteBorderColor: "#7aa2f7",
		darkMode: "true",
		fontFamily: "Poppins",
		fontSize: "18px",
	},
	startOnLoad: true,
	securityLevel: "strict" as const,
	flowchart: {
		htmlLabels: true,
		curve: "basis" as const,
		nodeSpacing: 60,
		rankSpacing: 60,
		useMaxWidth: true,
	},
	sequence: {
		useMaxWidth: true,
		diagramMarginX: 60,
		diagramMarginY: 15,
		actorMargin: 60,
		width: 180,
		height: 80,
		boxMargin: 15,
		boxTextMargin: 8,
		noteMargin: 15,
		messageMargin: 40,
		mirrorActors: true,
		bottomMarginAdj: 1,
		rightAngles: false,
		showSequenceNumbers: false,
		actorFontSize: 16,
		actorFontFamily: "Poppins, sans-serif",
		noteFontSize: 16,
		noteFontFamily: "Poppins, sans-serif",
		messageFontSize: 16,
		messageFontFamily: "Poppins, sans-serif",
	},
} as const;

export const DIAGRAM_TYPES = {
	graph: "Flowchart",
	flowchart: "Flowchart",
	sequencediagram: "Sequence",
	classdiagram: "Class",
	statediagram: "State",
	erdiagram: "ER",
	gantt: "Gantt",
	pie: "Pie Chart",
	journey: "User Journey",
	gitgraph: "Git Graph",
	mindmap: "Mindmap",
	timeline: "Timeline",
} as const;
