// config.ts
const authorConfig = {
  SiteName: "Abdul Rafay",
  SiteDescription:
    "Welcome to my universe, Software Engineer and Open Source enthusiast",
  name: "Abdul Rafay",
  jobTitle: "Software Engineer",
  position: "Full Stack & Flutter Developer",
  picture: "/author.jpg",
  socialLinks: {
    twitter: "https://twitter.com/future_insight9",
    linkedin: "https://linkedin.com/in/yourlinkedin",
    github: "https://github.com/rafay99-epic",
    upwork: "https://www.upwork.com/freelancers/~018c78c37a53bf3cac",
    youtube: "https://www.youtube.com/@BinaryBridgeHQ",
    whatsNumber: "+923035650798",
  },
  avator: "/favicon.png",
  webformKey: "", //add these keys
  hcaptchaSiteKey: "", //add these keys
  about: {
    whoAmI:
      "I'm a Full Stack Flutter Developer with a year's experience, transitioning from Machine Learning to crafting intuitive web experiences. Currently freelancing on platforms like Upwork, I deliver solutions that exceed client expectations.",
    lifeBeyondCode:
      "Beyond code, I find joy in life's simple pleasures – sipping coffee, engaging in video game battles, and embracing the challenge of new experiences. This holistic approach recharges my creativity and enriches my problem-solving perspective.",
    continuousLearning:
      "In my free time, I'm passionate about continuous learning. Thriving on the tech industry's dynamic challenges, I expand my skill set, always seeking growth. Let's collaborate and create something extraordinary!",
  },
  techStack: {
    "App Development": [
      "flutter",
      "android",
      "reactnative",
      "xamarin",
      "androidstudio",
      "xcode",
      "vscode",
      "intellijidea",
    ],
    "Frontend Development": [
      "astro",
      "tailwindcss",
      "nodejs",
      "react",
      "HUGO",
      "TypeScript",
      "Handlebars",
    ],
    "Backend Development": [
      "firebase",
      "docker",
      "mongodb",
      "mysql",
      "amazonwebservices",
      "googlecloudfunctions",
      "restapi",
      "graphql",
      "sqlite",
      "realm",
    ],
    "Cloud Computing": [
      "vercel",
      "aws",
      "linux",
      "Netlify",
      "Digital Ocean",
      "Microsoft",
    ],
    Essential: ["git", "github", "gitlab", "bitbucket", "sketch"],
    Scripting: ["powershell", "bash", "lua", "python"],
  },
  workExperience: [
    {
      companyName: "Daxno Technology",
      position: "Flutter Developer & Team Lead",
      employmentTime: "2nd Feb, 2024 - Present",
      roles: [
        "Building Stunning looking Android Applications",
        "Testing Multiple Applications",
        "Making sure the production does not go down",
      ],
      toolsUsed: [
        "Flutter",
        "VS Code",
        "Git",
        "Android Studio",
        "Firebase",
        "Superbase",
      ],
    },
    {
      companyName: "Swam Technology",
      position: "Machine Learning Engineer",
      employmentTime: "Sep, 2022 - Dec, 2023",
      roles: [
        "Expert in software design and machine learning model development",
        "Specialized in text analysis for abusive language detection",
        "Proven ability to apply machine learning to real-world problems",
        "Versatile skill set that bridges software engineering and advanced analytics.",
      ],
      toolsUsed: [
        "Python",
        "Flusk",
        "SQL Lite",
        "MongoDB",
        "Git",
        "TensorFlow",
      ],
    },
    {
      companyName: "Swam Technology",
      position: "Full Stack Web Developer",
      employmentTime: "Sep, 2022 - Dec, 2023",
      roles: [
        "Incorporated design principles to enhance navigation and readability.",
        "Implemented user-friendly CMS for law firm.",
        "Empowered non-technical users to manage website content seamlessly.",
        "Ensured intuitive design for easy content updates.",
      ],
      toolsUsed: [
        "HTML5",
        "JavaScript",
        "React",
        "NodeJs",
        "MongoDB",
        "Firebase",
      ],
    },
    {
      companyName: "Innovation Tech",
      position: "Intern",
      employmentTime: "2021",
      roles: [
        "Code review and testing responsibilities.",
        "Design of multiple user interfaces.",
        "Acquisition of significant knowledge through project involvement.",
        "Extensive test writing for various applications.",
      ],
      toolsUsed: ["Java", "XML", "Figma", "Firebase", "SQL Lite"],
    },
  ],
  projectData: [
    {
      title: "Simple Thread",
      description:
        "Simple Thread is a simple communication application developed using flutter and Firebase.",
      imageUrl: "/SimpleThread.png",
      technologies: [
        "Flutter",
        "Firebase",
        "Dart",
        "VS-code",
        "Git",
        "GitHub",
        "Postman",
        "Test Magic",
      ],
      githubLink: "https://github.com/rafay99-epic/Dienstleistro",
      deployedLink: "",
    },
    {
      title: "Dienstleisto",
      description:
        "Dienstleisto is a Flutter-based job-finding app designed to simplify your job search. With intuitive features and a user-friendly interface, find your next opportunity hassle-free.",
      imageUrl: "/DienstleistoIntroScreen.png",
      technologies: [
        "Flutter",
        "Firebase",
        "Dart",
        "VS-code",
        "Git",
        "GitHub",
        "Postman",
        "Test Magic",
      ],
      githubLink: "https://github.com/rafay99-epic/Dienstleistro",
      deployedLink: "",
    },

    {
      title: "Chess Master",
      description:
        "Dive into the strategic world of chess with this Flutter-powered game. Challenge friends 👥, master the art of checkmate! Your mobile chess arena awaits. ♞🌟",
      imageUrl: "/chessimage_chroped.png",
      technologies: [
        "Flutter",
        "Firebase",
        "Dart",
        "Postman",
        "Test Magic",
        "Git",
        "GitHub",
      ],
      githubLink: "https://github.com/rafay99-epic/ChessMaster",
      deployedLink: "",
    },
    {
      title: "Future Insight Flutter Application",
      description:
        "Explore insightful content effortlessly with the 'Clean UI Future Insight' Android App. Designed in Flutter for a seamless and immersive experience.",
      imageUrl: "/Thumbnail.png",
      technologies: [
        "Flutter",
        "Firebase",
        "Dart",
        "VS-code",
        "Google Play Store",
        "Git",
        "GitHub",
        "Postman",
        "Test Magic",
      ],
      githubLink: "https://github.com/FutureInsightTech/InsightfulFlutterApp",
      deployedLink: "",
    },
    {
      title: "Future Insight Website",
      description:
        "Explore cutting-edge insights on the 'Future Insight' Blog. Crafted with Node.js, Hugo, and deployed on Netlify for a seamless experience.",
      imageUrl: "/future-insight.png",
      technologies: [
        "Hugo",
        "NodeJs",
        "Markdown",
        "VS-code",
        "Git",
        "TinaCMS",
        "Netlify",
        "Playwrite",
        "SEO Optimization",
      ],
      githubLink: "https://github.com/FutureInsightTech/FutureIsnight-Site",
      deployedLink: "",
    },
    {
      title: "Shafiq Law Chamber",
      description:
        "Explore Shafiq Law Chamber's expertise on our seamlessly crafted website. Powered by Hugo and Node.js, it ensures a professional and user-friendly online presence.",
      imageUrl: "/shafiqLawChamber.png",
      technologies: [
        "Hugo",
        "NodeJs",
        "Markdown",
        "VS-code",
        "Git",
        "TinaCMS",
        "Netlify",
        "Playwrite",
        "SEO Optimization",
      ],
      githubLink: "https://github.com/FutureInsightTech/Shafiq-Law-Chamber",
      deployedLink: "https://shafiqlawchamber.com/",
    },
    {
      title: "Smart Parking Assistant",
      description:
        "Explore Parking Assistant: a reservation solution with ML recognition. Powered by Node.js, Python, and JavaScript, it streamlines operations for efficient parking management.",
      imageUrl: "/ParkingAssistant.png",
      technologies: [
        "HTML",
        "Netlify",
        "CSS",
        "Python",
        "JavaScript",
        "Arudino",
        "NodeJs",
        "VS-code",
        "Netlify",
        "Playwrite",
      ],
      githubLink: "https://github.com/FutureInsightTech/Parking-Assistant",
      deployedLink: "",
    },
  ],
};

export default authorConfig;
