name: Astro Build Check
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        
      - name: Run Astro check
        run: bun run check

      - name: Build Astro project
        run: bun run preview-build